### PR TITLE
Example schemes support for H5PYDataset

### PR DESCRIPTION
**Pull request by rizar**
This a starter implementation of support for examples schemes in H5PYDataset. I am interested in opinion, @vdumoulin , @dwf , should we have it?

### CODE REVIEW

**Comment by vdumoulin** [comment]
Short and sweet. I had a quick look and it looks good to me. I'll wait for the tests to pass and I'll have another look then.

**Comment by rizar** [comment]
Thanks for quick feedback! It still requires a test, but having your okay I will write it soon.

**Comment by dwf** [comment]
You should really, really use `numbers.Integral` for things like this, so that it catches numpy integer dtypes.

**Comment by rizar** [comment]
I am struggling to see how the test failures are related to the change I've made. @vdumoulin , can you please take a look?

**Comment by vdumoulin** [comment]
The "ValueError not raised" test failure arises because `True` is recognized as an integral number by `numbers.Integral`, and this is a value that's not supposed to make sense in the context of a request. I'm still working on the doctest failure.

**Comment by vdumoulin** [comment]
The doctest issue is really subtle: you're accessing `self.num_examples` in setting `self.example_iteration_scheme` *before* the superclass' `__init__` method has been called, which means that `sources` hasn't been set yet and the dataset is using the default `self.provides_sources`. This has the side effect of loading all sources in memory, which makes the doctest fail.

The error is fixed if you move that statement after the `super` call.

**Comment by rizar** [comment]
@vdumoulin , thanks for your help!

@dwf , can we have somehow get rid of `bool` as a representative of `numbers.Integral`?

**Comment by rizar** [comment]
@vdumoulin , I decided that in `test_value_error_out_of_memory_get_data` I can use something less ambiguous as `True` and now tests pass. I have to see however why coverage dropped.

**Comment by rizar** [comment]
@vdumoulin , any idea why this PR breaks `tests.test_server.TestServer.test_pickling`?

**Comment by dwf** [comment]
Sorry, didn't see your comment until now.

I don't really understand what you said about `bool` though.

**Comment by rizar** [comment]
I tried to ask if there exists `numbers.IntegralButNotBool` which includes `int` and `numpy.int` and etc. but not `bool`.

**Comment by dwf** [comment]
Oh. I see. I do not think so, no. :(

**Comment by dwf** [comment]
Oh man, what the hell Python:

In [9]: isinstance(False, int)
Out[9]: True

ಠ_ಠ

**Comment by rizar** [comment]
Okay, then I guess I was right that I changed the test to use `dict()` instead.

**Comment by vdumoulin** [comment]
@rizar What's the status on this PR?

**Comment by rizar** [comment]
Thanks for the reminder, I am going to finish it, say, this week.

**Comment by rizar** [comment]
Outdated, replaced by #282.

**Pull request closed without merging**
