### PR TITLE
Move Fuel install before Blocks install to tests against current Fuel…

### PR DESCRIPTION
**Pull request by vdumoulin**
… branch.

@bartvm Is this what you meant by "move `pip install .` before the Blocks install section"?

### CODE REVIEW

**Comment by vdumoulin** [comment]
Looks like it's more complicated than just moving the `pip install .` line before the Blocks install block: Fuel requires some packages that are installed within the Blocks install block

**Comment by rizar** [comment]
Should we also start testing `blocks-examples` here?

**Comment by vdumoulin** [comment]
We should first fix the `blocks-examples` test run time, but after that yes, it might be a good idea.

**Comment by rizar** [comment]
But aren't they fixed by https://github.com/mila-udem/blocks-examples/pull/12?

**Comment by vdumoulin** [comment]
What I mean is: since the LeNet example has been introduced, the test run time has jumped from ~10 minutes to ~38 minutes.

**Pull request merged**
