### PR TITLE
Fix missing packages preventing RTD to build

### PR DESCRIPTION
**Pull request by vdumoulin**

### CODE REVIEW

**Comment by vdumoulin** [comment]
@rizar do you mind having a quick look?

**Comment by bartvm** [comment]
Note that RTD doesn't allow the compilation of any C code on their servers, so I'm not sure it will be happy with you trying to install h5py and pyzmq. You might need to mock them instead: https://read-the-docs.readthedocs.org/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

**Comment by vdumoulin** [comment]
I'll have a look, thanks!

**Comment by dwf** [comment]
Do RTD support conda yet?

**Comment by vdumoulin** [comment]
It's been requested, but not yet: https://github.com/rtfd/readthedocs.org/issues/857.

**Comment by vdumoulin** [comment]
I'll merge to test @bartvm's suggested solution.

**Pull request merged**
