### PR TITLE
Update download links for CelebA files

### LINKED ISSUE #377: Built-in datasets: Convert still fails
I get this result when I try to convert the celeba dataset

```
fuel-convert celeba 64

Traceback (most recent call last):
  File "/usr/local/bin/fuel-convert", line 11, in <module>
    load_entry_point('fuel==0.2.0', 'console_scripts', 'fuel-convert')()
  File "/usr/local/lib/python2.7/dist-packages/fuel/bin/fuel_convert.py", line 79, in main
    output_paths = convert_function(**args_dict)
  File "/usr/local/lib/python2.7/dist-packages/fuel/converters/celeba.py", line 198, in convert_celeba
    directory, output_directory, output_filename)
  File "/usr/local/lib/python2.7/dist-packages/fuel/converters/base.py", line 45, in wrapped
    return f(directory, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fuel/converters/celeba.py", line 139, in convert_celeba_64
    h5file = _initialize_conversion(directory, output_path, (64, 64))
  File "/usr/local/lib/python2.7/dist-packages/fuel/converters/celeba.py", line 41, in _initialize_conversion
    skiprows=2, usecols=tuple(range(1, 41))) +
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 923, in loadtxt
    vals = [vals[i] for i in usecols]
IndexError: list index out of range
```

This is with the latest versions of Theano, Blocks and Fuel

### PR DESCRIPTION
**Pull request by vdumoulin**
Fixes #377.

### CODE REVIEW

**Comment by dmitriy-serdyuk** [comment]
Is it covered by tests?

**Comment by vdumoulin** [comment]
Not ATM. I don't see a straightforward way to add tests without requiring a complete download of some potentially very large files, though.

**Comment by dmitriy-serdyuk** [comment]
Seems that no. Maybe it worth checking if urls contain at least something (but not to download it) for all the downloaders. As a future work.

**Comment by vdumoulin** [comment]
In this specific case Dropbox returns something no matter what. Running `fuel-download celeba` with the old URLs downloaded HTML files corresponding to error pages.

**Comment by dmitriy-serdyuk** [comment]
Hmm, I see.

What does [this](https://github.com/mila-udem/fuel/blob/master/tests/test_downloaders.py#L169) do? Should it be updated?

**Comment by vdumoulin** [comment]
I just updated it. It verifies that the argument parser sets up properly.

**Comment by dmitriy-serdyuk** [comment]
Cool, LGTM if you checked locally.

**Pull request merged**
