### PR TITLE
Add tutorial for data processing server

### LINKED ISSUE #60: Document how to write a script that spawns a dataset server before training
Launching a combo dataset server/experiment script is going to be a pretty common use case. It'd be nice to include some sort of helper to make this as painless as possible.

### PR DESCRIPTION
**Pull request by vdumoulin**
Fixes #60.

### CODE REVIEW

**Comment by vdumoulin** [comment]
@dwf since you were the one creating the ticket, would you mind having a look at this to tell me if this is what you had in mind?

**Comment by bartvm** [comment]
This PR looks good to me actually, is there anything holding it back (besides the merge conflicts)? Else we should probably get it in. The Fuel server can be useful, but I still feel many people aren't aware of its existence or how to use it, this would help.

**Comment by vdumoulin** [comment]
Nothing that I'm aware of is holding it back, I think it just fell between the cracks. I'll rebase.

**Comment by vdumoulin** [comment]
Rebased, and the tests pass.

**Pull request merged**
