### PR TITLE
recover numpy.ndarray alignment after transmisson

### PR DESCRIPTION
**Pull request by Beronx86**
After transformation by start_server and DataServerStream, the numpy.ndarray may become unaligned.

### CODE REVIEW

**Comment by abergeron** [comment]
That will introduce a copy which is bad for performance.

**Comment by bartvm** [comment]
I guess you could do `data = [a if a.flags.aligned else numpy.require(a, requirements='A') for a in data]`?

**Comment by abergeron** [comment]
Or you could use copy=False which avoids the problem entirely.

**Comment by rizar** [comment]
@bartvm , I checked, it works.

**Pull request merged**
