### PR TITLE
enable fuel accept multiple data paths

### LINKED ISSUE #218: Make Fuel accept a list of paths as its data path in fuelrc
See [this comment](https://github.com/mila-udem/fuel/pull/214#discussion_r37345322).

### PR DESCRIPTION
**Pull request by hantek**
this PR tries to fix #218

### CODE REVIEW

**Comment by hantek** [comment]
This branch cannot not be automatically merged, I created another here: #227

**Comment by hantek** [comment]
I thought it is a typo... an r before the """

**Comment by vdumoulin** [comment]
For future reference, you could also have rebased on top of master and force-pushed on this branch, i.e.

```
$ git checkout master
$ git pull central master # assuming 'central' is the name of the remote for 'mila-udem/fuel'
$ git checkout datapath
$ git rebase master
$ git push -f origin master # assuming 'origin' is the name of the remote for 'hantek/fuel'
```

**Comment by hantek** [comment]
That's helpful. Yes I will do something like that next time ; )

**Pull request closed without merging**
