### PR TITLE
Update requirements, install fortran as temporary workaround

### PR DESCRIPTION
**Pull request by bartvm**

### CODE REVIEW

**Comment by rizar** [comment]
The build still fails, I cleared the cache and restarted.

**Comment by bartvm** [comment]
There seems to be a separate issue now, looks like this one: http://software-engineer.gatsbylee.com/python-pip-error-invalid-command-bdist_wheel/

**Comment by rizar** [comment]
Restarted the build to see if updating Blocks requirements helps.

**Comment by rizar** [comment]
Thank you very much @bartvm for fixing this!

**Pull request merged**
