### PR TITLE
H5PYDataset to support get_example_stream

### PR DESCRIPTION
**Pull request by rizar**
Looks like a very simple PR, a quick review would be appreciated. Replaces #179

### CODE REVIEW

**Comment by rizar** [comment]
Also fixes a few syntax errors that somehow were present in master.

**Comment by rizar** [comment]
@vdumoulin , doctests are somehow crashing for this pull request, which I find quite strange. Can you please comment on this test run: https://travis-ci.org/mila-udem/fuel/jobs/103674824 ?

**Comment by vdumoulin** [comment]
I confirm that the tests are failing locally for me as well.

**Comment by vdumoulin** [comment]
I found the source of the failure. If you move setting the `example_iteration_scheme` attribute after the superclass constructor call, the tests will pass.

This is a nasty issue: accessing the `num_examples` property causes the instance to access its `subsets` attribute, which is lazy-loaded. This causes `H5PYDataset.load` to be called *before* the `sources` attribute has been set, and then all data sources are loaded into memory as opposed to the ones specified by `sources`.

**Comment by vdumoulin** [comment]
I think we should document this quirk *really* well, as it's very easy to overlook.

**Comment by vdumoulin** [comment]
There's only one test failing ATM, and it's caused by the fact that `Subset.sorted_fancy_indexing` doesn't support integer requests.

**Comment by rizar** [comment]
Done, tests pass! @vdumoulin , do you have time to take a look?

**Comment by vdumoulin** [comment]
Looks good, thanks!

**Pull request merged**
