### PR TITLE
[requires.io] dependency update on master branch

### PR DESCRIPTION
**Pull request by bartvm**

### CODE REVIEW

**Comment by dwf** [comment]
Yeah... that didn't go so well.

**Comment by dwf** [comment]
@bartvm Any idea how this got so botched?

**Comment by bartvm** [comment]
Yeah, if Conda can't meet one of the requirements (new Pandas in this case) the entire command fails and it doesn't install anything. Travis happily goes on running tests though, which will consistently fail because even NumPy isn't available.

**Comment by bartvm** [comment]
Problem in general is that Conda's repositories seem to be 1-2 days behind PyPI, which means that these PRs initially always fail :/

**Comment by nouiz** [comment]
I received an email by requires.io for the hooks. I activated it.

**Pull request closed without merging**
