### PR TITLE
Make toy datasets deterministic.

### PR DESCRIPTION
**Pull request by dwf**
Adds a configurable seed that's popped off of kwargs if it's there, otherwise uses config.default_seed.

CC @jbornschein

### CODE REVIEW

**Comment by vdumoulin** [comment]
Good idea! LGTM.

**Comment by jbornschein** [comment]
Looks good to me. 

It obviously should have been done like this from the beginning.

**Comment by vdumoulin** [comment]
Merge at will when tests pass.

**Comment by dwf** [comment]
Scrutinizer errors do not relate to this PR.

**Pull request merged**
