### PR TITLE
WIP: Added a transformer to segment sequences. This is useful to apply tbptt.

### PR DESCRIPTION
**Pull request by sotelo**
I coded this transformer to segment sequences. I think it can be useful for people working with RNNs. The way I use it is to segment sequences in parts and so the gradient will not have to be propagated all the way back. You can also reuse the (final) states to initialize the initial_states to have some information about the past.

Please let me know if this is useful enough to be included in fuel. If that's the case, I'll clean up the code.

### CODE REVIEW

**Comment by rizar** [comment]
In my opinion it would be a valuable contribution to Fuel. A bit of work would be however required to make the docstring compliant with our standard. It should explain clearly what the transformer does without assuming that the reader know what TBPTT abbreviation means. That said, it would be still useful to mention it as the usecase in mind.

**Comment by sotelo** [comment]
Great to know! I should have a better version by the end of this week.

**Comment by vdumoulin** [comment]
@sotelo I'm doing a cleanup of the open PRs. Would you still like to go ahead with this one?

**Comment by sotelo** [comment]
Yes. I forgot to finish it a while ago. I will update it today.

**Comment by sotelo** [comment]
SORRY for the delay! I got distracted by other things and finally I am submitting some improvements for this. I've improved the documentation a bit and please let me know if you find it satisfactory. Also, I guess I am missing an example although I'm not really sure if I should do it with one of the existing datasets or create a synthetic one. Suggestions?

I am studying for technical interview, so I am still a bit busy but as soon as that is finished and this is also finished I will turn into the basic extension documentation.

**Comment by bartvm** [comment]
I missed this earlier, but I think this overlaps a lot with #310...

**Comment by sotelo** [comment]
Yes! It's very similar. There are a few differences though... The other one seems to be more for when you have only 1 large sequence. I'm using this one for instance for handwriting, where you have a lot of different length sequences and maybe you want to use tbptt.

**Comment by bartvm** [comment]
The window one I wrote should do the same thing and can take multiple,
variable length sequences (it was actually meant for TBTT on audio).

**Comment by sotelo** [comment]
I see now. Well, then I guess it's the same. I'll close the PR.

**Comment by bartvm** [comment]
The `add_flag` and `share_value` are missing from my implementation though

**Comment by bartvm** [comment]
Had another look and I think the implementations do something quite different. In my version, it takes e.g. `[1, 2, 3, 4, 5]` and turns it into e.g. `[1, 2, 3]`, `[2, 3, 4]` with targets `[4]` and `[5]`. Your version seems to take `[1, 2, 3, 4, 5]` and return `[1, 2]`, `[3, 4]`, `[5]`.

Basically, my transformer has two sliding windows (one becomes the source, the other the target) of fixed size, which slide with a step size of 1. Your version only has 1 window which has a step size equal to the window size, but the window size isn't fixed (and can be smaller for the end of the sequence).

I feel like they overlap enough though to see if we can combine all the functionality into one transformer, which basically has one or two sliding windows, a configurable step size, and configurable boundary conditions.

**Comment by sotelo** [comment]
Yes! I did it like that because I mostly use it for bpttt. Maybe we can talk next week for what should be the more complete transformer and I'll be happy to make the changes.

**Pull request closed without merging**
